version: '3.3'

services:
    server:
        image: log3990-server:prod
        depends_on:
            - postgres
        build:
            # context: ./packages/server
            target: server-prod
        ports:
            - ${SERVER_PORT:-5000}:3000
        environment:
            PG_HOST: postgres
            PG_PORT: 5432
            PG_USER: root
            PG_PASSWORD: uhdSAOUHhdsa87DSAUH7DSAHu
            PG_DATABASE: scrabble
            SERVER_URL: http://server:3000/api

    client:
        image: log3990-client:prod
        ports:
            - ${CLIENT_PORT:-80}:80
        build:
            # context: ./packages/client
            target: client-prod

    postgres:
        image: postgres
        restart: always
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: uhdSAOUHhdsa87DSAUH7DSAHu
            POSTGRES_DB: scrabble
        volumes:
            - db:/var/lib/postgresql/data

volumes:
    db:
        driver: local
